### ISSUE TITLE
Add source input to an action

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [rockem/create-opsgenie-alert-action#13]
Hello

Could you add a new input `source` to this action ?

**Comment by rockem** [comment]
It's definitely possible. 
Do you want to create a PR for it? (it might be faster)

**Comment by ievgenii-shepeliuk** [comment]
> It's definitely possible. Do you want to create a PR for it? (it might be faster)

Hello,
Unfortunately, I don't have time to research `GH action` internals to create a PR myself.

**Comment by rockem** [comment]
Implemented by (#14)

**Comment by ievgenii-shepeliuk** [comment]
Thanks a lot @rockem
