### ISSUE TITLE
Default priority "P3" is not set

### ISSUE THREAD

**Issue by alexanderluedeke** [rockem/create-opsgenie-alert-action#25]
Thanks for creating this action. 

I seems that "priority" is a mandatory field. But I guess the default P3 is not sent to OpsGenie API (see screenshot).

<img width="903" alt="SCR-20240503-kqpv" src="https://github.com/rockem/create-opsgenie-alert-action/assets/605542/6e88bb39-39d9-405b-a447-5ad646cceb69">

**Comment by rockem** [comment]
Thanks for the report
I've managed to replicate the issue and will take a look into it

**Comment by rockem** [comment]
Fixed on v1.3.0

**Comment by alexanderluedeke** [comment]
Thanks a lot. Great!
